= Deploying Generic Services in RHPDS

. Check out the git repo at https://github.com/rut31337/order_svc

. Order your services using `order_svc.sh`
.. Flag -c is the catalog in RHPDS
.. Flag -i is the catalog item name
.. Flag -u is your RHPDS _generic_ login
.. Flag -w is the cloudforms URL (RHPDS)
.. Flag -t specifies the number of instances to deploy
.. Flag -d allows you to set values that control the service deployment:
... Setting autostart=t will start the environments immediately upon creation and autostart=f will create environments but not start them
... Setting noemail=t is recommended as you do not want to send an email for every environment created (see obtaining GUIDs below)

----
./order_svc.sh -c "Workshops" -i "CloudForms 4.5 Workshop" \
 -u <generic_login> -w "https://rhpds.redhat.com" \
 -t 2 -d "autostart=t;noemail=t"
----

= Retrieving Lab GUIDs

. Obtain your GUIDs using this (flags are similar to order_svc, see above):
+
----
./get_svcs.sh -c "Workshops" -i "CloudForms 4.5 Workshop" \
 -u <generic_login> -w "https://rhpds.redhat.com" \
 -o services.txt
cat services.txt |cut -f5 -d- > guids.txt
----

= Working With Generic Environments

Once you have your GUIDs, you can share one GUID per student/group of students.  The lab instructions should be generic where each VM in the lab has a hostname of something-_$GUID_.rhpds.opentlc.com.  The student need only replace _$GUID_ with their assigned GUID.

= Retiring Generic Services in RHPDS

You have two options to retire services in RHPDS:

. Allow them to self retire

or 

. Use the standard service retirement in the RHPDS CloudForms interface. 
.. Services -> My Services
.. Select All
.. Lifecycle -> Retire

[IMPORTANT]
Please do not delete the services in Ravello directly.  You can power on and power off directly in Ravello if you want however.
